/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * fs-template
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../orval.mutator';
export type GetGreetingsParams = {
name: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getGreetingsResponse200 = {
  data: string
  status: 200
}

export type getGreetingsResponseSuccess = (getGreetingsResponse200) & {
  headers: Headers;
};
;

export type getGreetingsResponse = (getGreetingsResponseSuccess)

export const getGetGreetingsUrl = (params: GetGreetingsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/greetings?${stringifiedParams}` : `/api/greetings`
}

export const getGreetings = async (params: GetGreetingsParams, options?: RequestInit): Promise<getGreetingsResponse> => {

  return customFetch<getGreetingsResponse>(getGetGreetingsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetGreetingsQueryKey = (params?: GetGreetingsParams,) => {
    return [
    `/api/greetings`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetGreetingsQueryOptions = <TData = Awaited<ReturnType<typeof getGreetings>>, TError = unknown>(params: GetGreetingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGreetings>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGreetingsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGreetings>>> = ({ signal }) => getGreetings(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGreetings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGreetingsQueryResult = NonNullable<Awaited<ReturnType<typeof getGreetings>>>
export type GetGreetingsQueryError = unknown


export function useGetGreetings<TData = Awaited<ReturnType<typeof getGreetings>>, TError = unknown>(
 params: GetGreetingsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGreetings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGreetings>>,
          TError,
          Awaited<ReturnType<typeof getGreetings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGreetings<TData = Awaited<ReturnType<typeof getGreetings>>, TError = unknown>(
 params: GetGreetingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGreetings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGreetings>>,
          TError,
          Awaited<ReturnType<typeof getGreetings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGreetings<TData = Awaited<ReturnType<typeof getGreetings>>, TError = unknown>(
 params: GetGreetingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGreetings>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGreetings<TData = Awaited<ReturnType<typeof getGreetings>>, TError = unknown>(
 params: GetGreetingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGreetings>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGreetingsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
