name: Release Service

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      image_registry:
        required: true
        type: string
    secrets:
      GCP_CREDS:
        required: true

jobs:
  publish_image:
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP artifact registry
        uses: docker/login-action@v3
        with:
          registry: https://us-east4-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.GCP_CREDS }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image_registry }}/${{ inputs.service_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  update_deployment:
    runs-on: ubuntu-latest
    needs: publish_image
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDS }}

      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ inputs.service_name }}
          region: us-east4
          image: ${{ inputs.image_registry }}/${{ inputs.service_name }}:${{ needs.publish_image.outputs.image_version }}
