name: Publish docker images
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP artifact registry
        uses: docker/login-action@v3
        with:
          registry: https://us-east4-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.GCP_CREDS }}

      - name: Extract client metadata (tags, labels) for Docker
        id: client_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.IMAGE_REGISTRY }}/client

      - name: Build and push client Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: 'services/client.dockerfile'
          push: true
          tags: ${{ steps.client_meta.outputs.tags }}
          labels: ${{ steps.client_meta.outputs.labels }}

      - name: Extract server metadata (tags, labels) for Docker
        id: server_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.IMAGE_REGISTRY }}/server

      - name: Build and push server Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: 'services/server.dockerfile'
          push: true
          tags: ${{ steps.server_meta.outputs.tags }}
          labels: ${{ steps.server_meta.outputs.labels }}
