name: Release application
on:
  release:
    types: [published]
jobs:
  publish_client_image:
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.client_meta.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP artifact registry
        uses: docker/login-action@v3
        with:
          registry: https://us-east4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CREDS }}

      - name: Extract client metadata (tags, labels) for Docker
        id: client_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.IMAGE_REGISTRY }}/client

      - name: Build and push client Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/client.dockerfile
          push: true
          tags: ${{ steps.client_meta.outputs.tags }}
          labels: ${{ steps.client_meta.outputs.labels }}

  update_client_deployment:
    runs-on: ubuntu-latest
    needs: publish_client_image
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDS }}

      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: client
          region: us-east4
          image: ${{ vars.IMAGE_REGISTRY }}/client:${{ needs.publish_client_image.outputs.image_version }}

  publish_server_image:
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.server_meta.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP artifact registry
        uses: docker/login-action@v3
        with:
          registry: https://us-east4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CREDS }}

      - name: Extract server metadata (tags, labels) for Docker
        id: server_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.IMAGE_REGISTRY }}/server

      - name: Build and push server Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/server.dockerfile
          push: true
          tags: ${{ steps.server_meta.outputs.tags }}
          labels: ${{ steps.server_meta.outputs.labels }}

  update_server_deployment:
    runs-on: ubuntu-latest
    needs: publish_server_image
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDS }}

      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: server
          region: us-east4
          image: ${{ vars.IMAGE_REGISTRY }}/server:${{ needs.publish_server_image.outputs.image_version }}
